//go:build !noasm && darwin && arm64

// AUTO-GENERATED BY GOCC -- DO NOT EDIT

package gocc

import "unsafe"

//go:noescape,nosplit
func arm_add(a unsafe.Pointer, b unsafe.Pointer, c unsafe.Pointer, size uint64)
