// Code generated by command: go run main.go -out ./add_amd64.s -stubs ./add_stubs_amd64.go. DO NOT EDIT.

#include "textflag.h"

// func avx2_add(a []float32, b []float32, out []float32)
// Requires: AVX
TEXT ·avx2_add(SB), NOSPLIT, $0-72
	MOVQ a_base+0(FP), AX
	MOVQ b_base+24(FP), CX
	MOVQ out_base+48(FP), DX
	MOVQ a_len+8(FP), BX
	XORQ SI, SI

loop:
	VMOVDQU (AX)(SI*4), Y0
	VMOVDQU (CX)(SI*4), Y1
	VADDPS  Y0, Y1, Y0
	VMOVDQU Y0, (DX)(SI*4)
	ADDQ    $0x08, SI
	CMPQ    SI, BX
	JB      loop
	RET
