// Code generated by command: go run main.go -out ./add_amd64.s -stubs ./add_stubs_amd64.go. DO NOT EDIT.

package avo

// avx2_add adds a and b into out using AVX2 instructions.
func avx2_add(a []float32, b []float32, out []float32)
